# Generated by Django 4.1 on 2022-09-03 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('hora_apertura', models.DateField()),
                ('hora_cierre', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_estreno', models.DateField()),
                ('clasificacion', models.CharField(max_length=50)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema_api.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema_api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('hora_funcion', models.DateField()),
                ('cine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema_api.cine')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema_api.pelicula')),
            ],
        ),
        migrations.AddField(
            model_name='cine',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema_api.ciudad'),
        ),
        migrations.AddField(
            model_name='cine',
            name='tienda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema_api.tienda'),
        ),
    ]
