# Generated by Django 4.1 on 2022-09-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('ADMIN', 'admin'), ('CLIENT', 'client')], default='CLIENT', max_length=50)),
            ],
        ),
    ]
