# Generated by Django 4.1 on 2022-09-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('ADMIN', 'admin'), ('CLIENT', 'client')], default='CLIENT', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cine',
            name='hora_apertura',
        ),
        migrations.RemoveField(
            model_name='cine',
            name='hora_cierre',
        ),
        migrations.RemoveField(
            model_name='cine',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='año',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='fecha_estreno',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='hora_funcion',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='pelicula',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='producto',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='generos',
            field=models.ManyToManyField(to='cinema_api.genero'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(default='', upload_to='portada'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='productos',
            field=models.ManyToManyField(to='cinema_api.producto'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='cine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema_api.cine'),
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema_api.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema_api.sala')),
            ],
        ),
    ]
