# Generated by Django 4.1 on 2022-09-23 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_api', '0002_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cine',
            name='hora_apertura',
        ),
        migrations.RemoveField(
            model_name='cine',
            name='hora_cierre',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='año',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='fecha_estreno',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='hora_funcion',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='pelicula',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(default='', upload_to='portada'),
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema_api.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema_api.sala')),
            ],
        ),
    ]
